-- MySQL Script generated by MySQL Workbench
-- Sun Nov 27 17:46:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BasketballUnited
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BasketballUnited
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BasketballUnited` DEFAULT CHARACTER SET utf8 ;
USE `BasketballUnited` ;

-- -----------------------------------------------------
-- Table `BasketballUnited`.`Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BasketballUnited`.`Teams` ;

CREATE TABLE IF NOT EXISTS `BasketballUnited`.`Teams` (
  `teamID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `teamName` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `coachName` VARCHAR(45) NOT NULL,
  `numOfWins` INT UNSIGNED NOT NULL,
  `numOfLosses` INT UNSIGNED NOT NULL,
  `numOfChamps` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`teamID`),
  UNIQUE INDEX `teamID_UNIQUE` (`teamID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BasketballUnited`.`Positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BasketballUnited`.`Positions` ;

CREATE TABLE IF NOT EXISTS `BasketballUnited`.`Positions` (
  `positionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `positionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`positionID`),
  UNIQUE INDEX `positionID_UNIQUE` (`positionID` ASC) VISIBLE,
  UNIQUE INDEX `positionName_UNIQUE` (`positionName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BasketballUnited`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BasketballUnited`.`Players` ;

CREATE TABLE IF NOT EXISTS `BasketballUnited`.`Players` (
  `playerID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `height` INT UNSIGNED NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  `weight` INT UNSIGNED NOT NULL,
  `wingspan` INT UNSIGNED NOT NULL,
  `teamID` INT UNSIGNED NOT NULL,
  `positionID` INT UNSIGNED NOT NULL,
  `college` VARCHAR(45) NOT NULL,
  `jerseyNumber` INT UNSIGNED NOT NULL,
  `countryOfOrigin` VARCHAR(45) NOT NULL,
  `injuryStatus` ENUM('healthy', 'injured') NOT NULL,
  PRIMARY KEY (`playerID`),
  UNIQUE INDEX `playerID_UNIQUE` (`playerID` ASC) VISIBLE,
  INDEX `teamID_idx` (`teamID` ASC) VISIBLE,
  INDEX `positionID_idx` (`positionID` ASC) VISIBLE,
  CONSTRAINT `teamID`
    FOREIGN KEY (`teamID`)
    REFERENCES `BasketballUnited`.`Teams` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `positionID`
    FOREIGN KEY (`positionID`)
    REFERENCES `BasketballUnited`.`Positions` (`positionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BasketballUnited`.`Referees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BasketballUnited`.`Referees` ;

CREATE TABLE IF NOT EXISTS `BasketballUnited`.`Referees` (
  `refereeID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`refereeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BasketballUnited`.`Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BasketballUnited`.`Games` ;

CREATE TABLE IF NOT EXISTS `BasketballUnited`.`Games` (
  `gameID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `homeTeamID` INT UNSIGNED NOT NULL,
  `awayTeamID` INT UNSIGNED NOT NULL,
  `gameDate` DATE NOT NULL,
  `homeTeamScore` INT UNSIGNED NOT NULL,
  `awayTeamScore` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`gameID`),
  UNIQUE INDEX `gameID_UNIQUE` (`gameID` ASC) INVISIBLE,
  INDEX `homeTeamID_idx` (`homeTeamID` ASC) VISIBLE,
  INDEX `awayTeamID_idx` (`awayTeamID` ASC) VISIBLE,
  CONSTRAINT `homeTeamID`
    FOREIGN KEY (`homeTeamID`)
    REFERENCES `BasketballUnited`.`Teams` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `awayTeamID`
    FOREIGN KEY (`awayTeamID`)
    REFERENCES `BasketballUnited`.`Teams` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BasketballUnited`.`RefereeByGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BasketballUnited`.`RefereeByGame` ;

CREATE TABLE IF NOT EXISTS `BasketballUnited`.`RefereeByGame` (
  `gameID` INT UNSIGNED NOT NULL,
  `refereeID1` INT UNSIGNED NOT NULL,
  `refereeID2` INT UNSIGNED NOT NULL,
  `refereeID3` INT UNSIGNED NOT NULL,
  INDEX `refereeID1_idx` (`refereeID1` ASC) VISIBLE,
  INDEX `refereeID2_idx` (`refereeID2` ASC) VISIBLE,
  INDEX `refereeID3_idx` (`refereeID3` ASC) VISIBLE,
  INDEX `gameID_idx` (`gameID` ASC) VISIBLE,
  CONSTRAINT `refereeID1`
    FOREIGN KEY (`refereeID1`)
    REFERENCES `BasketballUnited`.`Referees` (`refereeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `refereeID2`
    FOREIGN KEY (`refereeID2`)
    REFERENCES `BasketballUnited`.`Referees` (`refereeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `refereeID3`
    FOREIGN KEY (`refereeID3`)
    REFERENCES `BasketballUnited`.`Referees` (`refereeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gameID`
    FOREIGN KEY (`gameID`)
    REFERENCES `BasketballUnited`.`Games` (`gameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BasketballUnited`.`GameLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BasketballUnited`.`GameLog` ;

CREATE TABLE IF NOT EXISTS `BasketballUnited`.`GameLog` (
  `gameID` INT UNSIGNED NOT NULL,
  `playerID` INT UNSIGNED NOT NULL,
  `points` INT UNSIGNED NOT NULL,
  `rebounds` INT UNSIGNED NOT NULL,
  `assists` INT UNSIGNED NOT NULL,
  `blocks` INT UNSIGNED NOT NULL,
  `steals` INT UNSIGNED NOT NULL,
  `turnovers` INT UNSIGNED NOT NULL,
  `fouls` INT UNSIGNED NOT NULL,
  `minutesPlayed` INT UNSIGNED NOT NULL,
  `seasonID` VARCHAR(45) NOT NULL,
  INDEX `playerID_idx` (`playerID` ASC) VISIBLE,
  INDEX `gameID_idx` (`gameID` ASC) VISIBLE,
  CONSTRAINT `playerID`
    FOREIGN KEY (`playerID`)
    REFERENCES `BasketballUnited`.`Players` (`playerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gameLogID`
    FOREIGN KEY (`gameID`)
    REFERENCES `BasketballUnited`.`Games` (`gameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BasketballUnited`.`Seasons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BasketballUnited`.`Seasons` ;

CREATE TABLE IF NOT EXISTS `BasketballUnited`.`Seasons` (
  `seasonID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `year` YEAR NOT NULL,
  UNIQUE INDEX `seasonID_UNIQUE` (`seasonID` ASC) VISIBLE,
  PRIMARY KEY (`seasonID`),
  UNIQUE INDEX `year_UNIQUE` (`year` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BasketballUnited`.`Accolades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BasketballUnited`.`Accolades` ;

CREATE TABLE IF NOT EXISTS `BasketballUnited`.`Accolades` (
  `accoladeID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `accoladeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`accoladeID`),
  UNIQUE INDEX `idAccolades_UNIQUE` (`accoladeID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BasketballUnited`.`AwardsByYear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BasketballUnited`.`AwardsByYear` ;

CREATE TABLE IF NOT EXISTS `BasketballUnited`.`AwardsByYear` (
  `seasonID` INT UNSIGNED NOT NULL,
  `playerID` INT UNSIGNED NOT NULL,
  `accoladeID` INT UNSIGNED NOT NULL,
  INDEX `seasonID_idx` (`seasonID` ASC) VISIBLE,
  INDEX `awardPlayerID_idx` (`playerID` ASC) VISIBLE,
  INDEX `accoladeID_idx` (`accoladeID` ASC) VISIBLE,
  CONSTRAINT `seasonID`
    FOREIGN KEY (`seasonID`)
    REFERENCES `BasketballUnited`.`Seasons` (`seasonID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `awardPlayerID`
    FOREIGN KEY (`playerID`)
    REFERENCES `BasketballUnited`.`Players` (`playerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `accoladeID`
    FOREIGN KEY (`accoladeID`)
    REFERENCES `BasketballUnited`.`Accolades` (`accoladeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
